# Blog info
blog_name: You Sci&Tech
slogan: Patience is bitter, but its fruit is sweet .
url: http://www.yifanyou.com

# Set avatar (Absolute url and relative url)
avatar: /images/lusuo.jpg

# Set favicon
favicon: /favicon.ico

# For seo
keywords: Sci, Tech, AION, Container

home_nav:
  - name: Blog
    url: http://blog.yifanyou.com
    target_blank: false #不在新页面打开
  - name: AION
    url: http://aion.yifanyou.com
    target_blank: true #在新页面打开
  - name: Github
    url: https://github.com/yifanyou
    target_blank: true
  - name: Twitter
    url: https://twitter.com/you8626
    target_blank: true

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 友链
    url: /link/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true # 在新页面打开
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: false # true|fase

# 盒子
toolbox:
  isShow: false # true|fase
  text: 盒子

search_slogan:
  isShow: false # true|fase
  text: Can you find the bug of world ~

link_slogan:
  isShow: false # true|fase
  text: 交换友链可以邮件


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: false
  btn_text: 支持一下
  tip: 扫一扫，支持
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/qr-wechat.png
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /images/qr-alipay.png

post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
personal_style: /css/personal-style.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
# blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics:

# Comment service
disqus_shortname:
# gitalk_shortname: forsigner
# hypercomments_id: 89821
# gentie_key: d16a7241e7cd4b389584ed8db2a4e8bc

#有言用户编号
#uyan_key:

# changyan_appid:
# changyan_appkey:

# gitment comment service
# gitment:
#     on: false  # true | false  这里开启
#     owner: # Your GitHub ID. Required.
#     repo: # The repository to store your comments. Make sure you're repo's owner. Required.
#     oauth: # An object contains your client ID and client secret. Required.
#         client_id: # GitHub client ID. Required.
#         client_secret: # GitHub client secret. Required.
#     id: # An optional string to identify your page. Default location.href.
#     title: # An optional title for your page, used as issue's title. Default document.title.
#     link: # An optional link for your page, used in issue's body. Default location.href.
#     desc: # An optional description for your page, used in issue's body. Default ''.
#     labels: # An optional array of labels your want to add when creating the issue. Default [].
#     theme: # An optional Gitment theme object. Default gitment.defaultTheme.
#     perPage: # An optional number to which comments will be paginated. Default 20.
#     maxCommentHeight: # An optional number to limit comments' max height, over which comments will be folded. Default 250.

# Valine comment system  https://valine.js.org
valine:
  enable: false # 如果使用valine，请设置改之为true
  appid:  # your leancloud application appid
  appkey:  # your leancloud application appkey
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: Just go go # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size

# 注意，多说即将关闭，建议选用上面四个评论系统
# duoshuo_shortname: forsigner



# 不算子,文章访问量统计和显示
busuanzi: false

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - ""
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@yifanyou"
    text_value_url: https://github.com/yifanyou
  # - type: weibo
  #   icon: icon-weibo
  #   text_key: 微博
  #   text_value: "@forsigner"
  #   text_value_url: http://weibo.com/u/1847075964
  # - type: mail
  #   icon: icon-mail
  #   text_key: Gmail
  #   text_value: "forsigner@gmail.com"
  - type: location
    icon: icon-location
    text_value: shanghai

link:
  - name: ssss
    info: 百度
    url: http://www.baidu.com/
    avatar: https://www.baidu.com

project:
  - type: personal
    name: fexo
    url: https://github.com/forsigner/fexo
    intro: A minimalist design theme for hexo
  # - type: company
  #   name: Fexo
  #   url: https://github.com/forsigner/fexo
  #   intro: A minimalist design theme for hexo
